In [11]:
import numpy as np

matx = np.array([[1,2],[5,4]])
maty = np.array([[0,3],[7,1]])

print("Given Matrix are :\n",matx,"\n\n",maty)
print("\nAddition of given matrix is:\n", np.add(matx,maty))
print("\nSubtraction of given matrix is:\n", np.subtract(matx,maty))
print("\nMultiplication of given matrix is:\n", np.multiply(matx,maty))
print("\nTranspose of given matrix are:\n", matx.T, "\n\n", maty.T)

Given Matrix are :
 [[1 2]
 [5 4]] 

 [[0 3]
 [7 1]]

Addition of given matrix is:
 [[ 1  5]
 [12  5]]

Subtraction of given matrix is:
 [[ 1 -1]
 [-2  3]]

Multiplication of given matrix is:
 [[ 0  6]
 [35  4]]

Transpose of given matrix are:
 [[1 5]
 [2 4]] 

 [[0 7]
 [3 1]]
